

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  server:
    build: ./server
    restart: unless-stopped
    depends_on:
      - mongodb
      - coturn
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/messenger?authSource=admin
      - JWT_SECRET=your_jwt_secret
      - TURN_SERVER=yourdomain.com
      - TURN_USERNAME=user1
      - TURN_PASSWORD=password1
    expose:
      - "3001"

  client:
    build: ./client
    restart: unless-stopped
    depends_on:
      - server
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server

volumes:
  mongodb_data: